#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 11 11:31:55 2020

@author: Charlie, Jonathan, Elaine, Chetana, Ashna
"""

from continuous_network import ContinuousHopfieldNetwork
import numpy as np
from functionDefinitions import calcPerf, simulate, TBI
import matplotlib.pyplot as plt

n_rows, n_cols = 28, 28
N = n_rows*n_cols

network = ContinuousHopfieldNetwork(N)

a, b = simulate(net=network, 
             pauseVal=0, 
             numPatterns=5, 
             patternIndex=2, 
             whitenVal=False, 
             plotVal=True, 
             tauVal=0.1, 
             itVal=50,
             density=0.02)

x, y = calcPerf(a, b, 28, 28, plotVal=True)

